### ISSUE TITLE
Change italics tags to a style

### ISSUE THREAD

**Issue by robinwhittleton** [aedattilo/ford-madox-ford_the-fifth-queen#4]
https://github.com/aedattilo/ford-madox-ford_the-fifth-queen/blob/f760b488f69922c74883db136f7fba72aa3a6ed2/src/epub/text/chapter-1-7.xhtml#L28-L30

Let’s remove the `<i>` tags from the verse: we can replace them with a style in local.css:
```css
#chapter-1-5 > blockquote{
  font-style: italic;
}
```
